# Generated by Django 5.2.4 on 2025-09-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.19, max_digits=4),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_con_iva',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_sin_iva',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Vendedor', 'Vendedor'), ('Cliente', 'Cliente')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='numero_documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='tipo_documento',
            field=models.CharField(default='CC', max_length=4),
        ),
    ]
