# Generated by Django 5.2.4 on 2025-09-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_producto_stock_alter_cliente_numero_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresaadmin',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
